### ISSUE TITLE
Ikea Rensare

### ISSUE THREAD

**Issue by Wouter-Lemoine** [derBroBro/boxcomp#5]
Would it be possible to include the Ikea Rensare packing cubes in this project?
They fit almost perfectly inside a 40x30 eurobox.

**Comment by derBroBro** [comment]
Sure, great idea! :)
Added in https://github.com/derBroBro/boxcomp/pull/6

**Comment by derBroBro** [comment]
Added it to the rendered site as well.
https://orglikea.pro/tools/box-compatibility/
